name: flutter_infinite_list_tdd_solid
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  collection: ^1.17.2
  dio: ^5.3.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.1
  stream_transform: ^2.1.0
dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  http_mock_adapter: ^0.6.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.1
  test: ^1.24.3
  very_good_analysis: ^5.1.0
flutter:
  uses-material-design: true
